a={"name":"shaoteng","age":28,"job":"dev"}
b=dict(name="shaoteng",age=28,job="dev")
print(a)
print(b)
####
k=['name','age','job']
v=['shaoteng',28,'dev']
c=dict(zip(k,v))
print(c)
f=dict.fromkeys(['name','age','job'])
print(f)
#通过[键]获取，若键不存在，则抛出异常
e=a['name']
print(e)
#通过get方法获取，如果键不存在，返回none，也可以指定默认返回对象
f=a.get('age')
g=a.get('zzz','null')
print(f)
print(g)
#列出所有键值对
h=a.items()
print(h)
#列出所有的键，所有的值
ak=a.keys()
av=a.values()
print(ak)
print(av)
